root: true

ignorePatterns:
  - "!.*"
  - /coverage
  - /dist
  - /node_modules
  - /test/fixtures/types.ts
  # parser raised unexpected error.
  - /src/lib/warnings.ts

extends:
  - plugin:@mysticatea/es2020

globals:
  console: "off"

rules:
  no-console: error
  "@mysticatea/ts/explicit-member-accessibility": "off"
  "@mysticatea/prettier": "off"

settings:
  node:
    tryExtensions:
      - .tsx
      - .ts
      - .mjs
      - .cjs
      - .js
      - .json
      - .node

overrides:
  - files: scripts/**
    rules:
      no-console: "off"

  - files: src/**
    rules:
      # Avoid iteration because transpiled code will inflate much.
      no-restricted-syntax: [error, ForOfStatement]
      "@mysticatea/prefer-for-of": "off"
